[project]
authors = ["josiahls <jklaivins@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "firehose"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
# Shell commands
shell = "pixi shell"
s = "pixi run shell"
p = "pixi run package"
bt = "pixi run build_test"


# firehose Development tools
## Just format the firehose src directory, not the tests.
format = "mojo format ."
f = "pixi run format"

## Common testing tasks
test_all = "mojo test -I . tests"
test_logger = "mojo run -I . tests/test_logger.mojo"
test_filterers = "mojo run -I . tests/filterers/test_default.mojo"
test_formatters = "mojo run -I . tests/formatters/test_default.mojo"

[dependencies]
mojo = ">=25.6.0.dev202508300"
